== Demo sample

This demo sets up

* Jenkins controller
* Jenkins agent
** JNLP inbound agent
** WebSocket agent
** SSH agent
* Otel collector
* Prometheus
* Jaeger
* Zipkin

=== 0. Setup Docker and Docker compose

- https://docs.docker.com/get-docker/
- https://docs.docker.com/compose/install/

=== 1. Build monitoring engine
....
$ mvn package -pl monitoring-engine
....

And wrote the monitoring engine path to `.env`

....
$ cd example
$ echo "MONITORING_ENGINE_JAR=../monitoring-engine/target/remoting-opentelemetry-engine.jar" >> .env
....

=== 2. Download custom remoting.jar

This plugin requires new feature of remoting.jar and the feature is not merged yet.
So please download remoting-4.11-rc2944.d6820234c35d.jar from incrementals: https://repo.jenkins-ci.org/ui/native/incrementals/org/jenkins-ci/main/remoting/4.11-rc2944.d6820234c35d/

And wrote the path of the JAR file to `.env`

....
$ echo "REMOTING_JAR=/path/to/remoting-4.11-rc2944.d6820234c35d.jar" >> .env
....

=== 3. Create SSH Public/Private Keys for SSH agent

....
$ ssh-keygen -f ./ssh-keys/id_ed25519 -t ed25519 -N p@ssword
....

And wrote the content of the public key, the path of the secret key and the password to `.env`

....
$ echo "SSH_PUBKEY=\"$(cat ./ssh-keys/id_ed25519.pub)\"" >> .env
$ echo "SSH_PRIVKEY_PATH=./ssh-keys/id_ed25519" >> .env
$ echo "SSH_PASSPHRASE=p@ssword" >> .env
....

=== 4. run
....
$ docker-compose up
....

It takes a few minutes to start.

=== 5. SSH agent

To collect ssh agent data,

....
$ cp /path/to/remoting-4.11-rc2944.d6820234c35d.jar ./jenkins-data/war/WEB-INF/lib/remoting-4.7.jar
$ docker-compose restart jenkins_blueocean
....

=== 5. Open Jaeger / Zipkin UI / Prometheus

Jaeger: http://localhost:16686/

Zipkin: http://localhost:9411/

Prometheus: http://localhost:9090/
