:toc: macro

= Contributing

toc::[]

== Source code contribution ways of working

* For larger contributions create an issue for any required discussion
* Implement solution on a branch in your fork
* Make sure to include issue ID (if created) in commit message, and make the message speak for itself
* Once you're done create a pull request and ask at least one of the maintainers for review
** Remember to title your pull request properly as it is used for release notes

== Run Locally

Prerequisites: _Java_ and _Maven_

* Ensure Java 8 or 11 is available.

[source, console]
----
$ java -version
----

* Use the alternate Java 8.

[source, console]
----
$ export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_252.jdk/Contents/Home
----

* Ensure Maven > 3.6.0 is installed and included in the PATH environment variable.

[source, console]
----
$ mvn --version
----

=== IDE configuration

See link:https://jenkins.io/doc/developer/development-environment/ide-configuration/[IDE configuration]

=== CLI

* Use the below commands.

[source, console]
----
$ mvn hpi:run
----

[source, console]
----
...
INFO: Jenkins is fully up and running
----

* Open <http://localhost:8080/jenkins/> to test the plugin locally.

Some plugins use multi module maven builds and you may need to change your `hpi:run` command to be run from the child directory, and build the other modules first.

[source, console]
----
$ mvn install -P quick-build
$ mvn -f plugin hpi:run
----

=== Configuration framework

We are creating and using simple configuration framework.

See link:./doc/dev/config.adoc[config documentation] for details
